clear all
a=[1 2 3;4 5 6;7 8 9];
b=[1 0 0;0 1 0;0 0 1];
c=a+b;
disp("A + B :");
disp(c);
c=a-b;
disp("A - B :");
disp(c);
c=a/b;
disp("A / B :");
disp(c);
c=a*b;
disp("A x B :");
disp(c);
disp("Sumation A :");
disp(sum(sum(a)));
disp("Sort A :");
disp(sort(a,'descend'));
disp("Transpose A :");
disp(transpose(a));
A = [1 -2 4; -5 2 0; 1 0 3];
disp("determinant A :");
disp(det(A));